### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by tachyon-ops** [ivaldi/brimir#108]
Hi,

I've managed to install brimir on my server... now I can login (tried once heh) but I can't logout... it apears 
"The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

So... since I'm new in ruby... is there a way I can debug? 
Thanks

**Comment by v60fan** [comment]
I'm having a similar issue to the original one report here. I've already tried a force refresh and different browses. I have tried doing theprecompile again a few times, no success. My css files and javascripts are not found. When I navigate directly to the URLs where they should be, I get file not found errors.

**Comment by frenkel** [comment]
Are the assets created when you finish precompiling? Is there a server like nginx or apache2 configured to serve those files?

-----Oorspronkelijk bericht-----
Van: "v60fan" <notifications@github.com>
Verzonden: ‎7-‎2-‎2015 16:58
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
CC: "Frank Groeneveld" <frank@ivaldi.nl>
Onderwerp: Re: [brimir] Can't log out (#108)

I'm having a similar issue to the original one report here. I've already tried a force refresh and different browses. I have tried doing theprecompile again a few times, no success. My css files and javascripts are not found. When I navigate directly to the URLs where they should be, I get file not found errors.

**Comment by v60fan** [comment]
So I have partially fixed my issue by running the bundle command as the rails user rather than as root. This allowed the login screen to use the proper css files. However, after successfully logging in, now I've got "We're sorry, but something went wrong" error. :-\ Previously, the assets were being created and I was ensuring they had the correct permissions, but something was obviously not quite right.

**Comment by v60fan** [comment]
I failed to mention also: I'm using nginx with unicorn.

**Comment by v60fan** [comment]
I've now gone through the README iteratively a few times and things seem to finally be up and running. My root cause was that I was running the install as root. I incorrectly read in other places that if I upgraded one of the gems, I could ignore this error. Sorry to bother you and thank you for replying.

**Comment by frenkel** [comment]
Great. If you have other issues, just let us know!
