### ISSUE TITLE
Compatibility with Postfix instead of Sendmail

### ISSUE THREAD

**Issue by ApfelUser** [ivaldi/brimir#153]
I would like to know:

1. is Brimir is compatible with Postfix?
2. If yes, how do I set it up?

because the `/etc/aliases` file is meant for sendfile. So how do I make

```
brimir: "|/bin/bash /path/to/your/brimir/repo/script/post-mail http://yoururl.com/tickets.json"
```

work in Postfix?

Thanks in advance

**Comment by frenkel** [comment]
That file works the same in postfix. We use it with postfix ourselves.

-----Oorspronkelijk bericht-----
Van: "ApfelUser" <notifications@github.com>
Verzonden: ‎25-‎1-‎2015 13:58
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
Onderwerp: [brimir] Compatibility with Postfix instead of Sendmail (#153)

I would like to know:
is Brimir is compatible with Postfix? 
If yes, how do I set it up? 
because the /etc/aliases file is meant for sendfile. So how do I make
brimir: "|/bin/bash /path/to/your/brimir/repo/script/post-mail http://yoururl.com/tickets.json"
work in Postfix?
Thanks in advance

**Comment by ApfelUser** [comment]
Well, this is not working on my setup. Are there any logs to find out why?

**Comment by frenkel** [comment]
What did you insert in /etc/aliases? If you added the line you posted before, you should change the path and url.

**Comment by ApfelUser** [comment]
Yeah, I've changed the path and URL to:

```
# /etc/aliases
mailer-daemon: postmaster
postmaster: root
nobody: root
hostmaster: root
usenet: root
news: root
webmaster: root
www: root
ftp: root
abuse: root
noc: root
security: root
root: adminuser
clamav: root
support: "|/bin/bash /srv/brimir/script/post-mail https://support.domain.tld/tickets.json"
```

**Comment by frenkel** [comment]
What do you see when you run something like this? Any errors?

`cat /srv/brimir/test/fixtures/ticket_mailer/simple | /srv/brimir/script/post-mail https://support.domain.tld/tickets.json`

**Comment by ApfelUser** [comment]
I am getting this and a new ticket as result:

```
{"id":1,"subject":"Testing this with a simple message","content":"This is a simple message to test the system.\n\nSome newlines here as well.\n","created_at":"2015-01-26T16:05:11.067Z","updated_at":"2015-01-26T16:05:11.067Z","assignee_id":null,"message_id":"AANLkTi=255AJgFEjx75oq3Y5UM=Q6L1jVCVz8oQq85ka@mail.gmail.com","user_id":2,"content_type":"text","status":"open","priority":"unknown"}
```

So it seems like a problem with Postfix. That's why I was asking for the compatibility.

**Comment by frenkel** [comment]
Do the mails bounce? Did you forget to run `newaliases` after editing /etc/aliases? (See `man newaliases`)

**Comment by ApfelUser** [comment]
Well, I see the emails if I log into my Account support@domain.tld. I also ran `newaliases` and `service postfix restart`

**Comment by frenkel** [comment]
Ah, by default postfix does not support having a mailbox and an aliases that are named exactly the same. In your setup it is probably first delivering to mailboxes and if it can't find one, it will deliver to aliases. Try renaming the alias, running `newaliases` and testing that new alias.

**Comment by ApfelUser** [comment]
I am getting this error if I delete the email:

```
Recipient address: support@domain.tld
  Reason: Remote SMTP server has rejected address
  Diagnostic code: smtp;550 5.1.1 <support@domain.tld>: Recipient address rejected: User unknown in virtual mailbox table
  Remote system: dns;email.domain.tld (TCP|11.111.111.111|11111|111.111.11.11|11) (domain.tld)

```

**Comment by frenkel** [comment]
I think your postfix is configured without aliases. Do other aliases exist and work?

-----Oorspronkelijk bericht-----
Van: "ApfelUser" <notifications@github.com>
Verzonden: ‎26-‎1-‎2015 17:40
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
CC: "Frank Groeneveld" <frank@ivaldi.nl>
Onderwerp: Re: [brimir] Compatibility with Postfix instead of Sendmail (#153)

I am getting this error if I delete the email:
Recipient address: support@domain.tld
  Reason: Remote SMTP server has rejected address
  Diagnostic code: smtp;550 5.1.1 <support@domain.tld>: Recipient address rejected: User unknown in virtual mailbox table
  Remote system: dns;email.domain.tld (TCP|11.111.111.111|11111|111.111.11.11|11) (domain.tld)

**Comment by ApfelUser** [comment]
That could be, but how do I check that? I've

```
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
```

enabled in my `/etc/postfix/main.cf`

**Comment by frenkel** [comment]
What do you have in the mydomains variable?
Op 26 jan. 2015 18:13 schreef "ApfelUser" <notifications@github.com>:

**Comment by frenkel** [comment]
I meant mydestination variable
Op 26 jan. 2015 21:45 schreef "Frank Groeneveld" <frank@ivaldi.nl>:

**Comment by ApfelUser** [comment]
Sorry for the late reply.

I got

```
mydestination = localhost, localhost.localdomain, localhost
```

in my `/etc/postfix/main.cf`

**Comment by frenkel** [comment]
Where is your actual domain in the config? Is it missing?

**Comment by ApfelUser** [comment]
Yeah, this is a setup not made by me. The guy who made is said the postfix configuration is for local email sending. I also have Dovecot running, which, according to him, is there for global email sending.

**Comment by ApfelUser** [comment]
I am sorry if I have a screwed up config. I also can go in the Postfix / Dovecot Forums if you want me to. Because this doesn't seem like a Brimir Problem.

**Comment by frenkel** [comment]
Yes, it won't work with local email sending. Dovecot is not used for email sending, it is used to give people access to their inbox (for example using IMAP or POP). I think the Postfix forums can help you better indeed.

**Comment by andryyy** [comment]
Hi,
He uses virtual transport for his public domain.
It was solved adding a non-virtual domain "xyz.domain.tld" to mydestination and creating an alias in "virtual_alias_map" from support@domain.tld to support@xyz.domain.tld. 
Looks like the pipe is not used in a postmap-hashed file.

**Comment by frenkel** [comment]
Ok, thanks for the info. We use a similar setup, but I didn't know he had virtual domains configured.

**Comment by andryyy** [comment]
You are welcome. Thanks to him I found out about Brimir. I am testing it right now. :-)
