### ISSUE TITLE
Add Label Dropdown when editing a Issue

### ISSUE THREAD

**Issue by 0x3333** [ivaldi/brimir#161]
In the Issue page is possible to add a label to it.

Would be nice to have a dropdown containing all labels available. Currently we have to type in the label.

Like in the user access control page.

**Comment by frenkel** [comment]
Yes, good suggestion. More people have asked for it, we haven't had the time to build it though.

**Comment by 0x3333** [comment]
Unfortunately, I don't code in ruby, otherwise I could write a patch.

Anyways, I'd like to keep it open in case you guys have a time to implement in the future.

Thanks

**Comment by frenkel** [comment]
I added it to `master`. Hope you like it, because we do :-)

**Comment by 0x3333** [comment]
Great!

I cannot test it because I use the hosted version in brimirapp.com. Do you know how often the hosted version is updated?

Thanks!

**Comment by frenkel** [comment]
Once a week usually. I'll try to deploy it monday.

-----Oorspronkelijk bericht-----
Van: "Tercio Gaudencio Filho" <notifications@github.com>
Verzonden: ‎20-‎2-‎2015 17:31
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
CC: "Frank Groeneveld" <frank@ivaldi.nl>
Onderwerp: Re: [brimir] Add Label Dropdown when editing a Issue (#161)

Great!
I cannot test it because I use the hosted version in brimirapp.com. Do you know how often the hosted version is updated?
Thanks!

**Comment by 0x3333** [comment]
Awesome! Thanks.

**Comment by frenkel** [comment]
All done, enjoy ;-)

**Comment by 0x3333** [comment]
Awesome! Perfect.
