### ISSUE TITLE
Brimir and automation, i want to add API features.

### ISSUE THREAD

**Issue by bsylvain** [ivaldi/brimir#210]
Hi, I was looking for a simple support ticket system in rails and I was ready to code my own but Brimir seems like a good solution. However it seems to misses a few features and instead of doing them on my own I would be interested to participate to Brimir.

My use case revolve around creating users and tickets from the API. The OAuth provider app will create a user account and a ticket assigned to that user. It will allow the user to connect using the OAuth provider.

### Manage users with the API

If I understood correctly, currently a user already created can set up google omniauth to login. The features I would need to do are : 

- Use the API to check if a user exist.
- Use the API to create a user.
- Setup the user via API with some kind of OAuth id so the app is able to match the user login through OAuth to the newly created account.
- Allow the user using OAuth to login with the correct profile

As I detailed that I realise I want to use OAuth as some kind of LDAP.

### Create a ticket with the API

Adding a create action to the current API does not seems too complicated, the only thing is it would necessitate is to remove the current notification logic from the create action to a service object or model hookups (after create etc).

This is more or less the roadmap of the changes I would like to do, what do you think about them?

I never really contributed to an open source project and I work solo on dev, so do not hesitate to tell me if my commits or tests are missing something.

**Comment by frenkel** [comment]
Hi,

These changes seem very reasonable to me. We will be able to merge them and provide you with feedback if you create small pull requests in a branch per change. For example:

- Create a branch "add_user_index_to_api_v1"
- Add everything to implement a get on `api/v1/users.json`
- Write tests for it
- Open a pull request for this branch to `brimir/master`

Then for the next feature:

- Create a new branch, based on the previous one named "add_user_create_to_api_v1"
- Add everything to implement a post on `api/v1/users.json`
- Write tests for it
- Open a pull request for this branch to `brimir/master`

Repeat till finished ;-)

Regarding the ticket notifications I would really like to have it in a separate service object, not as part of the model. Sending mails doesn't seem the responsibility of a model. I think it would be wise to create a separate branch with pull request for the refactoring step of moving the mail sending to the service object, because it allows us to make sure nothing breaks.

If you can think of a better way to authenticate to the API you're free to propose changes to that as well, because there are currently no known users of the API.
