### ISSUE TITLE
Is there anyway so i can install brimir on windows ?

### ISSUE THREAD

**Issue by synxmax** [ivaldi/brimir#234]
Hi there, 

i wanted to install brimir on my windows server 2012 r2 , i found this post on stackoverflow 

http://stackoverflow.com/questions/20464215/installing-open-source-ticket-manager-brimir

and i stoped proceeding, is this a bad idea installing brimir on windows , is there any guide on this ?

Thanks in advance

**Comment by frenkel** [comment]
Hi,

We have almost no experience running Ruby on Rails on the Windows platform. However, that doesn't mean it is impossible. First of, you'll need ghostscript and imagemagick to make attachment thumbnails work. If they exist and work correctly you can try installing from bundler (explained in the `README`).

The post you link to had an error because a certain gem in the Gemfile was not available anymore. This was fixed later on.

If you decide to try it out, let us know how it went!

**Comment by jmarmolejos** [comment]
Don't even try to, running rails apps on a Windows server is an uphill battle. Even if you get everything to work, you'll run into another block once you tried to get Capistrano working to automate deployments.

Been there, got the emotional scars.

**Comment by mlavadores** [comment]
Follow all the steps in this video install Postgres and git manager to windows OS and thats IT: https://www.youtube.com/watch?v=GwaeRJRoCeo  and to jmarmolejos its more easy and clean install Brimir onto the windows OS over the Debian. Good Luck Geeks!

**Comment by synxmax** [comment]
@mlavadores I will try it , almost forgot that this cool project exist, thanks for reply
