### ISSUE TITLE
alternate method to pull emails

### ISSUE THREAD

**Issue by hadifarnoud** [ivaldi/brimir#249]
It is not easy to setup pipe email and in some cases it does not make sense to do so.

It would be great to have IMAP pull or have a forward address (the way Zendesk and others work) as alternative to aliases pipe.

**Comment by frenkel** [comment]
What you are trying to configure on mail-in-a-box is a forward address such as Zendesk or our hosted Brimir solution uses.

IMAP pull doesn't seem as a great solution, because it would require a Rails job to run on a certain interval, it will never be real-time. I'll add this to the feature request list though.
