### ISSUE TITLE
Proposal: Use gemnasium for security alerts.

### ISSUE THREAD

**Issue by fiedl** [ivaldi/brimir#255]
Gemnasium is an external service that regularly checks for security alerts for dependencies — for free, since brimir is public.

* Have a badge turn red whenever there are security alerts.
* Receive security alerts via email.
* Security hints tell you what to do or which gems to update in order to fix the issue.

I can't do it via pull request, since this can only be done with the project owners github account.

https://gemnasium.com

**example badge:**
<img width="730" alt="bildschirmfoto 2016-01-27 um 18 31 43" src="https://cloud.githubusercontent.com/assets/1679688/12622227/9294a314-c524-11e5-9f37-2bad863c3154.png">

**example security alert:**
<img width="996" alt="bildschirmfoto 2016-01-27 um 18 33 19" src="https://cloud.githubusercontent.com/assets/1679688/12622226/9260c65c-c524-11e5-9491-bc80245e75da.png">

**Comment by frenkel** [comment]
I've just enabled it, but the badge is not very useful. It complains about Foundation being old (version 5 instead of 6), although 5 will stay maintained for at least a year from now on. I don't want people to have the wrong impression just by some badge displaying incorrect information. I'll keep gemnasium enabled, but won't be adding the badge for now.

**Comment by fiedl** [comment]
Good idea!
