### ISSUE TITLE
the same subject will generate multiply tickets

### ISSUE THREAD

**Issue by csskysea** [ivaldi/brimir#355]
suppose A is supporter, B is intermediary, C is customer

step 1: C send a request to B.
step 2: B forward C's request to A.
this will generate a ticket
step 3: A reply B.
step 4: B forward A's reply to C.
step 5: C reply B.
step 6: B forwad C's reply to A.
this will generate another ticket.

in fact, the two ticket is one subject. one subject need one ticket.

**Comment by frenkel** [comment]
When forwarding you lose the headers of an e-mail. Brimir uses the headers of an e-mail. It cannot create tickets based on subject, because that will result in problems when different people having the same subject. The only real solution would be to have a special word in the body of the e-mail. This is on the whishlist already.
