### ISSUE TITLE
Feature: Hide email signature and/or trailing quotes block

### ISSUE THREAD

**Issue by svoop** [ivaldi/brimir#442]
Think Github!

Say, I send the following email in reply to a Github issue: 

```
test - pls ignore (sven)

> This is the previous message.
> Nothing really quoteworthy here, but hey, let's quote it nonetheless!

---
Oh, and not to forget a signature in case you forgot who I am.
```

This is rendered on Github as follows:

<img width="796" alt="screen shot 2018-10-03 at 21 48 28" src="https://user-images.githubusercontent.com/7255/46435215-24019b00-c756-11e8-98ad-547610f81b82.png">

Behind the `...`, the email signature and trailing quotes block is hidden, click the dots to show it.

This makes life a whole lot easier when dealing with email oafs who always quote your entire message after their reply and/or have their mail client append a signature the length of the new testament.

**Comment by fiedl** [comment]
@svoop Have a look at #216. In our current implementation, we use https://github.com/fiedl/extended_email_reply_parser to get rid of the quotes and signatures.

This works very well for us in production. Including a "..." link did not work very well for several kinds of HTML mails. This is why we decided to just include a link to the raw email instead of a "..." link.

**Comment by svoop** [comment]
@friedl Thanks for the heads-up. I'll definitely take a look, however, it's not very high on my list quite yet. This may change though if more customers with large signatures come aboard.
